version: '3'

services:
    apache:
        build: .docker/apache
        container_name: symfony_apache
        ports:
          - "8000:80"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./app:/home/wwwroot/app
        depends_on:
          - php

    mysql:
        image: mysql
        ports:
          - "3307:3306"
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: symfony_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    php:
        build: .docker/php
        container_name: symfony_php
        volumes:
          - ./app:/home/wwwroot/app
        environment:
          - maildev_host=symfony_maildev
        depends_on:
          - maildev
          - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: symfony_maildev
        ports:
          - "8001:80"